spring:
  task:
    execution:
      pool:
        core-size: 10
        max-size: 25
        queue-capacity: 25
        keep-alive: "10s"
      thread-name-prefix: UpdateTask-
botio:
  multiThreadedUpdateConsumerEnabled: true
  perUserRequestLockingEnabled: true
